language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - opam remote add multicore https://github.com/ocamllabs/multicore-opam.git
  - opam switch 4.02.2+multicore
  - eval `opam config env`
  # TODO: Replace this with opam install . --deps-only when OPAM v2 becomes stable.
  - opam pin add reagents . -n
  - opam install -y --deps-only reagents
script:
  - eval `opam config env`
  - make all
env:
  global:
    - OCAML_VERSION=4.02
os:
  - linux
